
  {
    "name": "the-quad-worker",
    "compatibility_date": "2025-03-22",
    "main": "src/index.ts"
  }

# Add D1 binding for default environment
d1_databases = [
  { binding = "D1_DB", database_name = "the-quad-db", database_id = "e4c6f5c9-b43e-438a-b7b0-07d8a4db1fb2" }
]

# Add R2 binding for default environment
r2_buckets = [
  { binding = "R2_BUCKET", bucket_name = "images" }
]

[env.production]
workers_dev = true
route = "https://the-quad.pages.dev/*"
d1_databases = [
  { binding = "D1_DB", database_name = "the-quad-db", database_id = "e4c6f5c9-b43e-438a-b7b0-07d8a4db1fb2" }
]
r2_buckets = [
  { binding = "R2_BUCKET", bucket_name = "images" }
]